on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: "1.7.1"
      - name: build
        run: poetry build
      - name: release
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish -n --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD}
