on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"
      - uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: "1.7.1"
      - name: build
        run: poetry build
      - name: release
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish -n --username __token__ --password ${PYPI_API_TOKEN}
